In [8]:
import torch

torch.manual_seed(42)

a = torch.nn.LazyLinear(2)
print(a)
print(a.weight)
print(a.bias)

LazyLinear(in_features=0, out_features=2, bias=True)
<UninitializedParameter>
<UninitializedParameter>


In [9]:
x = torch.randn(1, 1)
y = a(x)
print(a)
print(a.weight)
print(a.bias)

Linear(in_features=1, out_features=2, bias=True)
Parameter containing:
tensor([[-0.2191],
        [ 0.2018]], requires_grad=True)
Parameter containing:
tensor([-0.4869,  0.5873], requires_grad=True)


In [10]:
a.weight.data.zero_()
a.weight.requires_grad = False
a.bias.data.fill_(1.0)
a.bias.requires_grad = False
print(a)
print(a.weight)
print(a.bias)

Linear(in_features=1, out_features=2, bias=True)
Parameter containing:
tensor([[0.],
        [0.]])
Parameter containing:
tensor([1., 1.])
